# Generated by Django 3.0.2 on 2020-01-12 16:22

import django.contrib.auth.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hiwi_portal', '0001_squashed_0017_fillerworkdustactivity_fixedworkdustactivity'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='hiwi',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='supervisor',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='worklog',
            name='overWork',
        ),
        migrations.RemoveField(
            model_name='worktime',
            name='date',
        ),
        migrations.RemoveField(
            model_name='worktime',
            name='hours',
        ),
        migrations.AlterField(
            model_name='contract',
            name='contract_begin',
            field=models.DateField(verbose_name='Vertragsstart'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='contract_end',
            field=models.DateField(verbose_name='Vertragsende'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='personell',
            field=models.CharField(choices=[('GF', 'Großforschungsbereich'), ('UB', 'Universitätsbereich')], max_length=2),
        ),
        migrations.AlterField(
            model_name='fillerworkdustactivity',
            name='avg_length',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='fixedworkdustactivity',
            name='avg_length',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.1)]),
        ),
        migrations.AlterField(
            model_name='fixedworkdustactivity',
            name='start',
            field=models.TimeField(verbose_name='Start'),
        ),
        migrations.AlterField(
            model_name='fixedworkdustactivity',
            name='week_day',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(4)]),
        ),
        migrations.AlterField(
            model_name='supervisor',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hiwi_portal.Department'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AlterField(
            model_name='worktime',
            name='activity',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='worktime',
            name='begin',
            field=models.DateTimeField(verbose_name='Start'),
        ),
        migrations.AlterField(
            model_name='worktime',
            name='end',
            field=models.DateTimeField(verbose_name='Ende'),
        ),
    ]
