# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-26 11:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hiwi_portal', '0020_auto_20160926_1054'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worktime',
            name='hours',
        ),
    ]
